# Generated by Django 5.0.6 on 2024-05-12 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kubernetes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Networking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpenStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CloudPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=50)),
                ('kubernetes', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='netmap.kubernetes')),
                ('network', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='netmap.networking')),
                ('openstack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='netmap.openstack')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('cloud_pools', models.ManyToManyField(to='netmap.cloudpool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('in_band_ip', models.GenericIPAddressField()),
                ('out_of_band_ip', models.GenericIPAddressField()),
                ('extra', models.JSONField(blank=True, null=True)),
                ('protocols', models.ManyToManyField(to='netmap.protocol')),
            ],
        ),
        migrations.CreateModel(
            name='KubernetesDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netmap.device')),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmap.kubernetes')),
            ],
            bases=('netmap.device',),
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netmap.device')),
                ('public_ip', models.GenericIPAddressField()),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmap.networking')),
            ],
            bases=('netmap.device',),
        ),
        migrations.CreateModel(
            name='OpenStackDevice',
            fields=[
                ('device_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netmap.device')),
                ('service', models.CharField(max_length=20)),
                ('infrastructure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmap.openstack')),
            ],
            bases=('netmap.device',),
        ),
    ]
