# Generated by Django 5.0.6 on 2024-05-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('is_base_model', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('in_band_ip', models.GenericIPAddressField()),
                ('out_of_band_ip', models.GenericIPAddressField()),
                ('manufacturer', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=25)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('is_editable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=50)),
            ],
        ),
    ]
