# Generated by Django 5.0.6 on 2024-05-12 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudpool',
            name='kubernetes',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='netmap.kubernetes'),
        ),
        migrations.AlterField(
            model_name='cloudpool',
            name='network',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='netmap.networking'),
        ),
        migrations.AlterField(
            model_name='cloudpool',
            name='openstack',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='netmap.openstack'),
        ),
    ]
