# Generated by Django 5.0.6 on 2024-06-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netmap', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloudpool',
            name='is_base_model',
        ),
        migrations.RemoveField(
            model_name='cloudpool',
            name='is_editable',
        ),
        migrations.RemoveField(
            model_name='cloudpool',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='kubernetesdevice',
            name='cloud_pool',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='cloud_pool',
        ),
        migrations.RemoveField(
            model_name='openstackdevice',
            name='cloud_pool',
        ),
        migrations.AddField(
            model_name='device',
            name='cloudpool',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='netmap.cloudpool'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AuthDevice',
            fields=[
                ('networkdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='netmap.networkdevice')),
                ('entry_point', models.GenericIPAddressField()),
                ('private_pool', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('auth_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netmap.protocol')),
            ],
            bases=('netmap.networkdevice',),
        ),
    ]
