# Generated by Django 5.0.6 on 2024-05-14 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netmap', '0002_alter_cloudpool_kubernetes_alter_cloudpool_network_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkmap',
            old_name='cloud_pools',
            new_name='cloudpools',
        ),
    ]
